export const img = {
  splashImg: require("../img/splashImg.png"),
  backGroundImg: require("../img/backGroundImg.png"),
  photoBookImg: require("../img/photoBookImg.png"),
  photoBookLessGradient: require("../img/photoBookLessGradient.png"),
  photoBookOrigin: require("../img/photoBookOrigin.png"),
  profileImg: require("../img/profileImg.png"),
  shoppingBagImg: require("../img/shoppingBagImg.png"),
  draftImg: require("../img/draftImg.png"),
  photoBook: require("../img/photoBook.png"),
  blueBag: require("../img/blueBag.png"),
  bookImg: require("../img/book.jpg"),
  singleBookImg: require("../img/singleBook.png"),
  colorModalImg1: require("../img/colorModalImg1.png"),
  colorModalImg2: require("../img/colorModalImg2.png"),
  colorModalImg3: require("../img/colorModalImg3.png"),
  colorModalImg4: require("../img/colorModalImg4.png"),
  singleBookSvg: require("../img/bookListSvg.svg"),
  singleBookTester: require("../img/singleBookTester.png"),
  singleBookTester2: require("../img/bookListTester2.png"),
  singleBookTester3: require("../img/singleBookTester3.png"),
  editImage: require("../img/editImage.png"),
  filter1: require("../img/filter1.png"),
  filter2: require("../img/filter2.png"),
  filter3: require("../img/filter3.png"),
  filter4: require("../img/filter4.png"),
  filter5: require("../img/filter5.png"),
};
