import {StyleSheet} from 'react-native';
import {hp, wp} from '../../utils/reponsiveness';

export const styles = StyleSheet.create({
  backgroundImage: {
    position: 'absolute',
    top: 0,
    width: '109.5%',
    height: '104%',
  },
  topTextContainer: {
    position: 'absolute',
    alignSelf: 'center',
    width: '100%',
    height: 20,
    borderWidth: 1,
    borderStyle: 'dotted',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    backgroundColor: 'transparent',
  },
  bottomTextContainer: {
    position: 'absolute',
    alignSelf: 'center',
    width: '100%',
    height: 20,
    borderWidth: 1,
    borderStyle: 'dotted',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    backgroundColor: 'transparent',
  },
  dynamicText: {
    textAlign: 'center',
  },
  pageIndicatorWrapper: {
    position: 'absolute',
    bottom: hp(-4),
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10000,
  },
  pageNumberBox: {
    backgroundColor: 'rgba(0,0,0,0.7)',
    paddingHorizontal: wp(3),
    paddingVertical: wp(1.5),
    borderRadius: wp(4),
    marginRight: wp(2),
  },
  pageNumberText: {
    color: 'white',
    fontSize: wp(4),
    fontWeight: 'bold',
    textAlign: 'center',
  },
  goToButton: {
    position: 'absolute',
    top: wp(2),
    right: wp(2),
    backgroundColor: '#4688BA',
    width: wp(12),
    height: wp(12),
    borderRadius: wp(6),
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 50000,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 15,
  },
  goToButtonText: {
    color: 'white',
    fontSize: wp(6),
    fontWeight: 'bold',
    textAlign: 'center',
  },
  greyLine: {
    position: 'absolute',
    backgroundColor: '#E2E2E2',
  },
  spineShadow: {
    width: wp(1.25),
    position: 'absolute',
    zIndex: 300,
    shadowColor: 'grey',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 10,
  },
  bottomPageNumber: {
    backgroundColor: 'black',
    zIndex: 200,
    position: 'absolute',
    bottom: 0,
    alignSelf: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
  },
  bottomPageNumberText: {
    color: 'white',
    fontSize: 13,
  },
});
